server:
  port: 8081

logging:
  level:
    root: INFO
    com.example: DEBUG
  config: classpath:logging/logback-spring.xml

management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      remote-fields:
        - request-id
      correlation:
        fields:
          - request-id
      enabled: true

spring:
  cloud:
    discovery:
      enabled: false
    gateway:
      routes:
        - id: demo
          uri: http://localhost:8080
          predicates:
            - Host=localhost:8081